### ISSUE TITLE
Issue with Loading .MAT files of the Repository

### ISSUE THREAD

**Issue by kassroman** [MarcoTodescato/Sync-Aware-State-Estimator#3]
Hi sir, 
I have downloaded these codes
But I am unable to open the .MAT files in the data folder.
I am unable to load these .MAT files. Could you please help me to load these files?

There is gitattributes file and I have tried to clone the repository from the instructions from this website- https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository
Cloning was successful, however, I am still unable to load the .mat files 

Could you please tell me the PROCEDURE to LOAD these .MAT files?

**Comment by MarcoTodescato** [comment]
Hi there,

sorry to hear you are not able to load the data. However, there is no fancy procedure to load the .mat files.

One question for me to understand: are you able to download the data but not to load them in Matlab?  or you are not even able to download them from GitHub?
Which kind of error do you get?

**Comment by kassroman** [comment]
Hi Sir,

Thank you very much for your quick reply.

I have already downloaded the .mat files. While I am trying to open in MATLAB software, it shows an error as follows.

*********************
Error using load:
Unable to read MAT-file. Not a binary MAT-file. Try LOAD -ASCII to read as text.
*********************

I think MATLAB is unable to open the file in work-space due to files contain the ASCII type instead of Binary number, that's why it shows an error.
Any additional requirement is there to open this file?

**Comment by MarcoTodescato** [comment]
Hi there, 

I am afraid you might have not downloaded properly the .mat files. What are the sizes of the files?

I suggest you do one of the following.

Approach 1. use Git LFS:
1. Install Git LFS in your system
2. Clone (do not download as a zip) the repository using `git lfs clone path/to/the/repo` 

Approach 2. without Git LFS:
1. Clone the repository running `git clone path/to/the/repo`
2. Make sure the .mat files have different sizes. Otherwise install Git LFS and run `git lfs pull --include *.mat`

You can try to follow either one of the above approaches, however, currently, you might not be able to clone the repo since I reached the monthly data quota for the repo. If this is the case, you should be able to clone again at the beginning of next month.

If you still encounter some issues, you can also contact the GitHub team how to best proceed.

**Comment by vlsrinivas** [comment]
Hi Marco 
Much thanks for this valuable input! Appreciate your research.
And thanks kassroman for rising this issue.

I did face the same issue as kassroman pointed it out, when I tried them a couple of weeks back. I think there is some problem with the .mat files (as I see the size of ALL .mat files is only 1kB!!) . Also, I did try cloning using git lfs, yet my endeavours could not let me load the .mat files. And then I gave up.

To get rid of this difficulty at this point, could you simply please mail the .mat to my email id- lakshmi.scedantham.eee11@itbhu.ac.in
Atleast, only those .mat files corresponding to the smaller system 5-node EPFL? (data with1EEE-123 bus could obviously be large size)

Will you be so kind to mail them? It would indeed be helpful for my research and of course, I would cite your works more.

Thanking you anyways.

**Comment by vlsrinivas** [comment]
sorry, email id is- lakshmi.svedantham.eee11@itbhu.ac.in (before mentioned has a typo)

**Comment by MarcoTodescato** [comment]
HI vlsrinivas,

thanks for your message. The .mat files being all of 1KB is most likely due to git LFS not downloading the data correctly. When cloning LFS tracked files, git usually does not really download them but use placeholders instead. That is why you see all files being of the same (small size).

What exactly have you tried?

You need to force git to download the files and, if I remember correctly, this can be achieved via `git lfs pull --include=*.mat` 
or using the appropriate path to the mat file.

I would urge to try this and tell me what happens. So, in case this works, I can add proper documentation for that.

Again, the monthly data quota has most likely been reached so you will not be able to download the data until the end of the month.

I am honestly not really in favor of start sending data via email.

Cheers.

**Comment by vlsrinivas** [comment]
Hi Marco,
Thanks for quickly getting back.

I am sorry to say that even the above procedure does not fetch me any of the .mat data. The attached 'capture 1' is the error I received.

What exactly I have done a few days back is depicted in 'capture 2' attached below. This did work for rest of files, however, I received incorrect 1kb .mat files which is the problem.

So, unfortunately, it seems that all the gates are closed for me, to access these .mat files. Some help is greatly appreciated. 

Anyways, cheers and thanks for your support.
 

![capture 1](https://user-images.githubusercontent.com/74904642/100162149-d05ce900-2eaa-11eb-98b7-a0e92065adc7.JPG)
![capture 2](https://user-images.githubusercontent.com/74904642/100162151-d0f57f80-2eaa-11eb-8ba7-afc1921066cd.JPG)

**Comment by MarcoTodescato** [comment]
Hi vlsrinivas,

thanks for the screenshots.

The git messages are showing exactly what I was talking about, that is the data quota limit is preventing you to pull. 

There are two issues:

1. In the first screenshot, I am not 100% sure but I think, when using `git lfs pull --include=` you should use the relativa path inside the repo rather than the https url. It would be nice to see the log message anyway.

2. In the second screenshot, as you can see in the logged message you can read
`batch response: this repository is over its data quota ...`
This is what preventing you guys to download the data. Unfortunately the quota is not very high, so if you try to download 2 or 3 times you can already hit it!

**Comment by vlsrinivas** [comment]
Hi Marco,

Thankyou for the message.

1. Yes, I have tried to using the path inside the repo as well, however, I received the same error message (see capture 3). The log message in either case is as in the 'capture 4' attached below.

2. Secondly, if it is data quota issue, then I will try in the beginning of the next month. Since 1GB is the allocated free monthly usage, 2-3 times.. you mean.. the repository .mat files are too large as large as around 400MB!.. Okay, anyways, I will try next month.

Thankyou for your support Marco.

![Capture 3](https://user-images.githubusercontent.com/74904642/100226155-3c753680-2f17-11eb-80f3-a1f4611c6ae2.JPG)
![Capture 4](https://user-images.githubusercontent.com/74904642/100226158-3e3efa00-2f17-11eb-85e9-77d913490211.JPG)

**Comment by MarcoTodescato** [comment]
Hi vlsrinivas,

thank you for getting back with the logs.

Yes, the total data is a bit less that 300MB. That is why the data are tracked with Git LFS.

Suggestion: since it is 25th of the month, just give it a try at the beginning of next month. If it still doesn't work, write here again.

Cheers.

**Comment by vlsrinivas** [comment]
Hi Marco,

Sure, then, I will try it again the next moth starting and still if it doesn't work, I will write here again with some hope.

Many thanks for your support. Have a good day. bye.

**Comment by vlsrinivas** [comment]
Hi Marco,
Hope you had a nice week end!

As discussed before, I tried to clone the repository with the same procedure as in the command prompt image (2nd image in our overall discussion).  Yet, I wonder the same message is getting repeated ( depicting that repository is over its data quota). The same issue goes with the pull command as well.

May be you may try clone one sample .mat file (ex. epfl case.mat), try once on your PC, and see if it is working. If it works for you, then you may inform me the procedure/ changes in the way I needed to clone. 

Thank you once again for your efforts.

**Comment by MarcoTodescato** [comment]
Hi again vlsrinivas,

I am sorry to hear there still troubles. Apparently the number of clones already caused the fill up the quota. I will resolve this issue by deleting and recreating the current repo without using Git LFS and by linking the data to an external URL to be downloaded. Hope this helps.

I suggest you to check my github page tomorrow or so, to look for the new repo (it will be called the same). 
When I delete this repo also this issue will be closed.

**Comment by MarcoTodescato** [comment]
Deleting repo and recreating w/o using git LFS. Repo will be available soon with the same name

**Comment by vlsrinivas** [comment]
oh! 
I am really sorry for causing you as much inconvenience, if I did. Anyway, it is your repo and I appreciated your hard work. Thanks.

**Comment by MarcoTodescato** [comment]
no worries. It is good you brought it up. So maybe I can find a more stable solution ;-)
